### PR TITLE
Spot count v0.3.0

### PR DESCRIPTION
**Pull request by scottberry**
Added Nico and Thomas' module as a native matlab jterator module. Seems very robust on TissueMAPS v0.2.2 (I have run large experiments), and also runs on v0.3.0 (I have done some small tests).

I also added a python module called apply_mask which I needed to remove spots outside cells, but is quite general. Finally I added a python module for plotting label images, because I couldn't figure out the matlab functionality for nice label images.

### CODE REVIEW

**Comment by scottberry** [comment]
requires https://github.com/TissueMAPS/JtLibrary/pull/13

**Comment by hackermd** [comment]
How is `apply_mask` different from the existing `relabel` module? Could this be combined into one module? Could you please add a docstring for the `main()` function.

What's the purpose of `plot_label_image` module? Couldn't you plot the label image in whatever module that created the image in the first place?

**Comment by scottberry** [comment]
```apply_mask``` allows a set of objects in a binary or label image to be filtered based on their overlap with a second binary or label image. In general it is not necessary that these be relabeled after filtering. Moreover, I was not aware that ```relabel``` removes not overlapping objects, is it true? In my workflow ```apply_mask```  is necessary to be able to perform aggregate measurements of subobjects within cells or nuclei, for example.

**Comment by scottberry** [comment]
When I wrote this, I could not find the functionality to create a labelled-image plot with intelligent alternating color scheme for different objects in matlab ```plotting.m```. ```plot_label_image``` is a  workaround which could be replaced now with changes to ```plotting.m```, or replaced later once this functionality is in place.

**Comment by hackermd** [comment]
> apply_mask allows a set of objects in a binary or label image to be filtered based on their overlap with a second binary or label image. In general it is not necessary that these be relabeled after filtering.

I would maybe leave the relabeling out of this module, since it would change the type of your input mask. Users can make use of the `relabel` module in case relabeling is desired. When `mask` is a binary image, `masked_image` would be a labeled image and this may not be intended.

In addition, you should make a copy of `objects`, or in case objects should be relabeled not perform this operation in place, otherwise `objects` will be modified, which would prevent downstream modules from using it in its unmodified form.

**Comment by hackermd** [comment]
> plot_label_image is a workaround which could be replaced now with changes to plotting.m, or replaced later once this functionality is in place.

Could you replace that, i.e. create the figure within the matlab module itself using the functions provided by `plotting.m`?

**Pull request closed without merging**
